# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/imgages" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # PAGES
  - name: "page"
    label: "Page"
    folder: "my_pages"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "page-title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "markdown", required: false}
      - {label: "Call to action", name: "cta", widget: "boolean"}
      - label: "Image"
        name: "image"
        widget: "image"
        media_library:
          config:
            multiple: true
      - {label: "Permalink", name: "permalink", widget: "string"}
      - label: "Sitemap"
        name: "sitemap"
        widget: "object"
        fields: 
        - {label: "Lastmod", name: "lastmod", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  # Collections
  - name: "tariff"
    label: "Tariff"
    folder: "my_collections/_tariffs"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "tariff-title", widget: "string", tagname: "h1"}
      - {label: "Number of sessions", name: "number_sessions", widget: "number", valueType: int}
      - {label: "Frequency", name: "frequency", widget: "number", valueType: int}
      - {label: "Price", name: "price", widget: "number", valueType: int}
      - {label: "URL ID", name: "url_id", widget: "number", valueType: int}
  - name: "topic"
    label: "Topic"
    folder: "my_collections/_topics"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "topictitle", widget: "string", tagname: "h1"}
      - {label: "Icon", name: "icon", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
